// Copyright (C) 2022 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
// SPDX-License-Identifier: MIT
//
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

syntax = "proto3";
package ansys.api.acp.v0.butt_joint_sequence;
option go_package = "github.com/ansys/ansys-api-acp/ansys/api/acp/v0/butt_joint_sequence";

import "ansys/api/acp/v0/base.proto";
import "ansys/api/acp/v0/enum_types.proto";

message PrimaryPly {
    base.ResourcePath sequence = 1;
    int64 level = 2;
}

enum DefinitionType {
    // Manual mode matches the wire default for backwards compatibility: When
    // a server or client does not support automatic butt joint detection, it
    // will be treated as manual mode.
    // Note that the GUI / scripting default is instead AUTOMATIC_ALL_PLY_TYPES.
    MANUAL = 0;
    AUTOMATIC_ALL_PLY_TYPES = 1;
    AUTOMATIC_CORE_MATERIALS = 2;
    AUTOMATIC_IDENTICAL_PLY_TYPE = 3;
    AUTOMATIC_SIMILAR_PLY_TYPES = 4;
    AUTOMATIC_ISOTROPIC_MATERIALS = 5;
    AUTOMATIC_REINFORCED_MATERIALS = 6;
    AUTOMATIC_IDENTICAL_MODELING_PLY_MATERIAL = 7;
}

message Properties {
    enum_types.StatusType status = 1;
    bool active = 2;
    int64 global_ply_nr = 3;

    // Ply sequences if definition_type is MANUAL.
    repeated PrimaryPly primary_plies = 4;
    repeated base.ResourcePath secondary_plies = 5;

    DefinitionType definition_type = 6;

    // Ply sequences if definition_type is AUTOMATIC_*.
    repeated base.ResourcePath starting_modeling_plies = 7;
    repeated base.ResourcePath automatically_added_sequences = 8; // read-only
}

message ObjectInfo {
    base.BasicInfo info = 1;
    Properties properties = 2;
}

message ListReply { repeated ObjectInfo objects = 1; }

message BatchGetReply {
    repeated ObjectInfo successful_replies = 1;
    repeated base.BatchItemError failed_items = 2;
}

message BatchPutRequest { repeated ObjectInfo put_requests = 1; }

message BatchPutReply {
    repeated ObjectInfo successful_replies = 1;
    repeated base.BatchItemError failed_items = 2;
}

message CreateRequest {
    base.CollectionPath collection_path = 1;
    string name = 2;
    Properties properties = 3;
}

message ConvertToManualDefinitionRequest { base.BasicInfo info = 1; }

service ObjectService {
    rpc List(base.ListRequest) returns (ListReply);

    rpc Get(base.GetRequest) returns (ObjectInfo);
    rpc BatchGet(base.BatchGetRequest) returns (BatchGetReply);

    rpc Put(ObjectInfo) returns (ObjectInfo);
    rpc BatchPut(BatchPutRequest) returns (BatchPutReply);

    rpc Delete(base.DeleteRequest) returns (base.Empty);

    rpc BatchDelete(base.BatchDeleteRequest) returns (base.BatchDeleteReply);

    rpc Create(CreateRequest) returns (ObjectInfo);

    rpc ConvertToManualDefinition(ConvertToManualDefinitionRequest)
        returns (base.Empty);
}
