// Copyright (C) 2022 - 2026 Synopsys, Inc. and ANSYS, Inc. All rights reserved.
// SPDX-License-Identifier: MIT
//
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.

syntax = "proto3";
package ansys.api.acp.v0.hdf5_composite_cae_import;
option go_package = "github.com/ansys/ansys-api-acp/ansys/api/acp/v0/hdf5_composite_cae_import";

import "ansys/api/acp/v0/base.proto";
import "ansys/api/acp/v0/enum_types.proto";
import "ansys/api/acp/v0/import_object.proto";

// Default CRUD messages

enum ImportMode {
    APPEND = 0;
    OVERWRITE = 1;
}

enum ProjectionMode {
    SHELL = 0;
    SOLID = 1;
}

message ShellMappingProperties {
    // MAPPING SCOPE
    optional bool all_elements = 1;
    repeated base.ResourcePath element_sets = 2;

    // TOLERANCES
    optional double relative_thickness_tolerance = 3;
    optional double relative_in_plane_tolerance = 4;
    optional double angle_tolerance = 5;
    optional double small_hole_threshold = 6;
}

message SolidMappingProperties {
    optional enum_types.OffsetType offset_type = 1;
}

message CoordinateTransformation {
    // all angles are in degrees
    double rotation_angle_x = 1;
    double rotation_angle_y = 2;
    double rotation_angle_z = 3;
    double translation_x = 4;
    double translation_y = 5;
    double translation_z = 6;
}

message Properties {
    // READ-ONLY PROPERTIES
    bool has_run = 1;

    // GENERAL SETTINGS
    string path = 2;
    optional ProjectionMode projection_mode = 3;

    // PLY ANGLES (both modes)
    optional double minimum_angle_tolerance = 4;
    optional bool recompute_reference_directions = 5;

    // SHELL MAPPING PROPERTIES
    ShellMappingProperties shell_mapping_properties = 6;

    // SOLID MAPPING PROPERTIES
    SolidMappingProperties solid_mapping_properties = 7;

    // COORDINATE TRANSFORMATION
    CoordinateTransformation coordinate_transformation = 8;
}

message ObjectInfo {
    base.BasicInfo info = 1;
    Properties properties = 2;
}

message ListReply { repeated ObjectInfo objects = 1; }

message CreateRequest {
    base.CollectionPath collection_path = 1;
    string name = 2;
    Properties properties = 3;
}

service ObjectService {
    rpc List(base.ListRequest) returns (ListReply);

    rpc Get(base.GetRequest) returns (ObjectInfo);

    rpc Put(ObjectInfo) returns (ObjectInfo);

    rpc Delete(base.DeleteRequest) returns (base.Empty);

    rpc Create(CreateRequest) returns (ObjectInfo);

    // Special Import Object RPCs

    rpc Run(import_object.RunRequest) returns (base.Empty);

    rpc ListGeneratedObjects(import_object.ListGeneratedObjectsRequest)
        returns (import_object.ListGeneratedObjectsReply);

    rpc DeleteGeneratedObjects(import_object.DeleteGeneratedObjectsRequest)
        returns (base.Empty);
}
