version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    versioning-strategy: "increase"
    cooldown:
      include:
        - '*'
      default-days: 7
    exclude-paths:
      - "pyproject.toml" # build dependencies in pyproject.toml use open intervals
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      include:
        - '*'
      default-days: 7
