name: GitHub CI

# run only on main branch.  This avoids duplicated actions on PRs
on:
  pull_request:
  push:
    tags:
      - "*"
    branches:
      - main

env:
  MAIN_PYTHON_VERSION: '3.9'
  PACKAGE_NAME: 'ansys-api-acp'

jobs:
  build-library:
    name: "Build package"
    runs-on: ubuntu-latest
    steps:
      - name: "Build library source and wheel artifacts"
        uses: ansys/actions/build-library@v4
        with:
          library-name: ${{ env.PACKAGE_NAME }}

  check-version:
    name: "Check version is bumped"
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.base.ref == 'main'
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v2
      - name: "Check version is changed"
        run: |
          git fetch origin $BASE_BRANCH

          VERSION_FILE=$(find src/ -name VERSION)

          NUM_CHARS=$(git diff --ignore-all-space origin/$BASE_BRANCH -- $VERSION_FILE | wc -c)

          if [ $NUM_CHARS -eq 0 ]; then
            echo "Version is not bumped.  Please update the version in $VERSION_FILE"
            exit 1
          fi
        env:
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}


  release-pypi-private:
    name: "Release to private PyPI"
    runs-on: ubuntu-latest
    needs: [build-library]
    if: github.event_name == 'push' && github.ref_type == 'branch' && github.ref == 'refs/heads/main'
    steps:
      - name: "Release to the private PyPI repository"
        uses: ansys/actions/release-pypi-private@v4
        with:
          library-name:  ${{ env.PACKAGE_NAME }}
          twine-username: "__token__"
          twine-token: ${{ secrets.PYANSYS_PYPI_PRIVATE_PAT }}
